controllers/kustomization_controller.go, internal/lockedfile/internal/filelock/filelock.go, internal/lockedfile/internal/filelock/filelock_unix.go, internal/lockedfile/lockedfile.go, internal/lockedfile/lockedfile_filelock.go, internal/lockedfile/mutex.go
Prevent concurrent apply of the same kustomization using tmp file locking.
=> Add locking to kustomization apply

.github/workflows/e2e.yaml, .github/workflows/release.yml, Dockerfile, config/manager/deployment.yaml, controllers/gitrepository_predicate.go, controllers/kustomization_controller.go
End-to-end workflow with Kubernetes Kind:
- build and deploy kustomize-controller
- deploy source-controller
- apply sample kustomizations and git repositories
- check that kustomization apply was successful
=> Add e2e tests

README.md, config/manager/deployment.yaml, controllers/gitrepository_controller.go, controllers/kustomization_controller.go, controllers/kustomization_predicate.go, main.go
Changes:
- add JSON log format cmd flag
- format apply output as a map of object/operation
- add apply logs to docs
=> Introduce JSON logging

README.md, docs/spec/v1alpha1/README.md
Create spec doc for `kustomize.fluxcd.io/v1alpha1` API.
=> Kustomize API specification v1alpha1

.github/workflows/e2e.yaml, README.md
=> Cleanup e2e tests

config/crd/kustomization.yaml, config/default/kustomization.yaml, config/default/namespace.yaml, config/manager/deployment.yaml, config/manager/kustomization.yaml, config/rbac/kustomization.yaml
Make the controller deploy config reusable for different namespaces.
=> deploy: reusable config

.github/workflows/e2e.yaml, Dockerfile, README.md, controllers/kustomization_controller.go, controllers/kustomization_predicate.go
Perform a two stage GC, remove cluster level objects first, then namespaced objects.
=> gc: remove non-namespaced objects first

docs/spec/v1alpha1/README.md, docs/spec/v1alpha1/kustomization.md, docs/spec/v1alpha1/profile.md
Allow cluster admins to define RBAC for kustomizations.
=> spec: Role-based access control

controllers/gitrepository_controller.go
* log namespaced Kustomization name
* do not log success message on annotation failure
* change log messages to better reflect reality
=> controllers: GitRepositoryWatcher log improvements

api/v1alpha1/sort.go, api/v1alpha1/sort_test.go, controllers/gitrepository_controller.go
=> Sort dependencies with Tarjan's SCCS algorithm

README.md, controllers/gitrepository_watcher.go, controllers/kustomization_controller.go, docs/spec/README.md
Wait for a workload (Deployment/DaemonSet/StatefulSet) to be created before running the liveness check.
=> Improve health checking

Dockerfile, go.mod, go.sum
Add support for [valueAdd](https://github.com/kubernetes-sigs/kustomize/blob/master/examples/valueAdd.md) builtin transformer.
=> Update kustomize to v3.6.1

Makefile, api/v1alpha1/doc.go, api/v1alpha1/kustomization_types.go, api/v1alpha1/profile_types.go, docs/api/kustomize.md, hack/api-docs/config.json, hack/api-docs/template/members.tpl, hack/api-docs/template/pkg.tpl, hack/api-docs/template/type.tpl
=> Generate API documentation

controllers/kustomization_controller.go, main.go
Add command argument for configuring the interval at which failing dependencies are reevaluated.
=> Configurable dependency requeuing

CHANGELOG.md, config/default/kustomization.yaml, config/manager/kustomization.yaml, go.mod, go.sum
This is the first prerelease ready for public testing.
=> Release v0.0.1

config/manager/deployment.yaml, main.go
Use same port as source/helm/notification controllers
=> Change metrics port to 8080

controllers/kustomization_controller.go
Changes:
- return reconciliation error so that controller runtime metrics record failures
- change structure logging labels to match the controller runtime format
- prevent spurious info events by issuing events only when revision changes
Ref: https://github.com/fluxcd/toolkit/issues/94
=> Improve error handling and reporting

api/v1alpha1/kustomization_types.go, controllers/kustomization_controller.go, controllers/kustomization_predicate.go
Ref: https://github.com/fluxcd/toolkit/issues/89
=> Refactor garbage collector to finalizer

api/v1alpha1/kustomization_types.go, config/crd/bases/kustomize.fluxcd.io_kustomizations.yaml, controllers/kustomization_controller.go, docs/api/kustomize.md, docs/spec/v1alpha1/kustomization.md
Ref: https://github.com/fluxcd/toolkit/issues/125
=> Take observed generation of dependencies into account

Makefile
=> Make various targets work after api pkg change

controllers/kustomization_controller.go
=> Fix GC ignore unknown resource kind

controllers/kustomization_controller.go
Ref: https://github.com/fluxcd/toolkit/issues/206
=> Fix GC snapshot

api/v1alpha1/reference_types.go, config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml, controllers/kustomization_controller.go, controllers/kustomization_healthcheck.go, docs/api/kustomize.md, docs/spec/v1alpha1/kustomization.md, main.go
Changes:
* Refactor kstatus health check
* Add kstatus compatible kinds to health assessment docs
=> Update health assessment docs

controllers/kustomization_controller.go
Related to:
https://github.com/fluxcd/notification-controller/issues/45
=> Send event when reconcile succeeds with update metadata

.github/workflows/release.yml, Dockerfile
Ref: https://github.com/fluxcd/toolkit/issues/246
=> Publish ARM v7/v8 multi-arch image to GHCR

Makefile, README.md, docs/spec/README.md, docs/spec/v1beta1/kustomization.md
Rename the default namespace to `gotk-system` .
=> Set default namespace to gotk-system

.github/workflows/e2e.yaml, .github/workflows/fossa.yml, .github/workflows/release.yml, CHANGELOG.md, README.md, docs/internal/release.md
Ref: https://github.com/fluxcd/toolkit/issues/152
=> Set default branch to main

docs/spec/v1beta1/kustomization.md
Ref: https://github.com/fluxcd/toolkit/issues/319
=> Add namespace to API docs examples

controllers/kustomization_controller.go
=> Set correct status on failure events

CHANGELOG.md, Dockerfile, Makefile, README.md, config/default/kustomization.yaml, config/manager/kustomization.yaml, docs/spec/README.md, docs/spec/v1beta1/kustomization.md, go.mod, go.sum
Ref: https://github.com/fluxcd/toolkit/issues/388
=> Release v0.2.0

Dockerfile
=> Add openssh client to support git+ssh Kustomize resources

config/manager/deployment.yaml
Ref: https://github.com/fluxcd/flux2/issues/457
=> Add fsGroup to security context

docs/spec/v1beta1/kustomization.md
Replace Istio with cert-manager in the dependsOn example.
=> Use cert-manager example for dependsOn docs

controllers/kustomization_gc.go
Log the GC query errors to help diagnose objects skipped from pruning, ref: #217 
To enable these GC logs, the controller should be installed using `flux install/bootstrap --log-level=debug`
=> Add debug logs to garbage collection

controllers/kustomization_decryptor.go
Signed-off-by: Nicolas Lamirault <nicolas.lamirault@gmail.com>
=> Add SOPS user error to logs

Makefile, api/go.mod, api/go.sum, controllers/kustomization_controller.go, go.mod, go.sum
To include a bug fix to the `ReconcilateAtChangedPredicate`
and renaming to `ReconcileRequestedPredicate`.
=> Upgrade runtime package to v0.6.2

controllers/kustomization_controller_test.go
Fixes an issue in the tests where the KC running would use the shells kubeconfig to when reconciling and no the in memory test cluster. The tests would pass before because there were no checks of the resources that were being added.
=> Specify kubeconfig in tests

controllers/kustomization_decryptor.go
Fixes https://github.com/fluxcd/source-controller/issues/296
Signed-off-by: David J. M. Karlsen <david@davidkarlsen.com>
=> Avoid prompts on import by adding batch flag to gpg

controllers/kustomization_controller.go
Signed-off-by: Florian Richter <floririchte@gmail.com>
=> Fixed small typos

api/go.mod, api/go.sum, go.mod, go.sum
Followup: https://github.com/fluxcd/pkg/pull/96
=> Update fluxcd/pkg/runtime to v0.10.2

api/go.mod, api/go.sum, go.mod, go.sum
=> Update fluxcd/pkg/apis/meta to v0.9.0

api/v1beta1/kustomization_types.go, config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml, docs/api/kustomize.md, docs/spec/v1beta1/kustomization.md
Fix: https://github.com/fluxcd/website/issues/337
=> Add the generic patch field to the API spec docs

controllers/kustomization_controller_test.go
Add UT test for kustomization controller, Steps as:
1.  Create kustomization with depend on
2.  Kustomization Obj status should equal with DependencyNotReadyReason
3.  Get resource fail for kustomization not ready
=> Test kustomization depend on for improve ut

.github/workflows/e2e.yaml, Dockerfile
Changes:
- Update Alpine to v3.14
- Update kubectl to v1.21.2
=> Update Alpine v3.14 and kubectl v1.21.2

controllers/kustomization_controller_gc_test.go
Signed-off-by: Vincent Boutour <bob@vibioh.fr>
=> Add test for prune toggling

controllers/kustomization_controller_gc_test.go
Fix for operation cannot be fulfilled on kustomizations.kustomize.toolkit.fluxcd.io "e7e0v": the object has been modified; please apply your changes to the latest version and try again.
=> Fix generation conflicts in tests

controllers/kustomization_controller_gc_test.go, controllers/kustomization_controller_patch_test.go, controllers/kustomization_indexers.go, controllers/utils.go
Replace old utility function ObjectKey with controller-runtime's
client.ObjectKeyFromObject.
=> Remove old util ObjectKey

controllers/kustomization_controller_patch_test.go, controllers/testdata/replacement/kustomization.yaml, controllers/testdata/replacement/quota.yaml
This pull request adds a test to ensure the Kustomize replacement transformer works in the controller.
Closes #396
=> Add kustomize replacement transformer test

controllers/kustomization_healthcheck.go
Before this change, the controller would panic. The new behaviour introduced in this PR causes the following event to be recorded:
```
0s          Normal   error    kustomization/test   Health check failed for [Job 'default/neo4j-bootstrap-databases' (status 'Unknown'): no matches for kind "Job" in group ""]
```
fixes #432
Signed-off-by: Max Jonas Werner <mail@makk.es>
=> fix: don't skip all errors when recording health check status

controllers/kustomization_controller.go, controllers/kustomization_decryptor.go, controllers/kustomization_decryptor_test.go, controllers/kustomization_generator.go, internal/sops/pgp/keysource.go
Fixes: https://github.com/fluxcd/kustomize-controller/issues/472
Related to: https://github.com/fluxcd/flux2/issues/1658
=> chore: remove deprecated io/ioutil

internal/sops/pgp/keysource.go
Some of these error messages were likely imported from somewhere else.
=> Lowercase first letters for fmt.Errorf messages

go.mod, go.sum
kustomize v4.4.1 [changelog](https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv4.4.1)
=> Update controller to kustomize v4.4.1

docs/spec/v1beta2/kustomization.md
=> Fix typo in API spec docs

go.mod, go.sum
Fix for CVE-2021-30465 and CVE-2021-41190
=> Restore runc and image-spec patches

controllers/kustomization_controller.go
Following example of fluxcd/source-controller#542, fluxcd/helm-controller#395
=> Use patch instead of update when adding finalizers

.github/workflows/release.yml, .goreleaser.yaml, Dockerfile
This PR implements:
- https://github.com/fluxcd/flux2/issues/2302
- https://github.com/fluxcd/flux2/issues/2303
=> Publish SBOM and sign release artifacts

.github/workflows/cifuzz.yaml, .github/workflows/e2e.yaml, .github/workflows/nightly.yml, .github/workflows/rebase.yml, .github/workflows/scan.yml
Improve GITHUB_TOKEN permissions in the workflows.
Signed-off-by: Soule BA <bah.soule@gmail.com>
=> Add Permissions to github Workflows

go.mod, go.sum
Changes:
- Update `sigs.k8s.io/kustomize/api` to v0.11.1
https://github.com/kubernetes-sigs/kustomize/releases/tag/api%2Fv0.11.1
- Update `sigs.k8s.io/kustomize/kyaml` to v0.13.3
https://github.com/kubernetes-sigs/kustomize/releases/tag/kyaml%2Fv0.13.3
=> Update controller to kustomize v4.5.1

docs/spec/v1beta2/kustomization.md
Signed-off-by: Daniel Holbach <daniel@weave.works>
=> Fix typo in API docs

controllers/kustomization_controller.go
Closes https://github.com/fluxcd/kustomize-controller/issues/572
=> Fixed typo : If applied, this commit will ensure no grammatical errors

CHANGELOG.md
Signed-off-by: Stefan Prodan <stefan.prodan@gmail.com>
=> Add Azure Key Vault integration to changelog

go.mod, go.sum
Ref: https://github.com/fluxcd/flux2/issues/2574
=> Update Kustomize to v4.5.3

docs/spec/v1beta2/kustomization.md
Add example of deploying applications from Git to production environments.
=> Add recommended settings to API docs

CHANGELOG.md
Signed-off-by: Daniel Holbach <daniel@weave.works>
=> update toolkit.fluxcd.io docs link

controllers/kustomization_controller.go, main.go
https://github.com/fluxcd/kustomize-controller/issues/617
=> feat: flags to configure exponential backoff retry

controllers/kustomization_generator.go, controllers/kustomization_generator_test.go, controllers/kustomization_transformer_test.go, controllers/testdata/patch/deployment.yaml
Fixes: #652 
This pull request sets the image digests from the
=> Set digests in image override

controllers/kustomization_generator_test.go, controllers/testdata/relbase/clusters/base/configmap.yaml, controllers/testdata/relbase/clusters/base/kustomization.yaml, controllers/testdata/relbase/clusters/patches.yaml, controllers/testdata/relbase/clusters/staging/flux-system/kustomization.yaml, controllers/testdata/relbase/clusters/staging/flux-system/secret.yaml
Tests directory structure as described in https://github.com/fluxcd/flux2/issues/1522#issuecomment-1126802642.
=> generator: test secure build relative base dir

go.mod, internal/sops/awskms/keysource_test.go
=> sops/awskms: fix compatibility tests with upstream sops

docs/spec/v1beta2/kustomization.md
=> Fix typo from pune to prune

go.mod, go.sum
https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv4.5.6
=> Update controller to kustomize v4.5.6

controllers/kustomization_controller.go
Signed-off-by: Santosh Kaluskar <dtshbl@gmail.com>
Implements RecoverPanic option on reconciler.
part of [issue #2952](https://github.com/fluxcd/flux2/issues/2952#issue-1325576799)
=> Enable RecoverPanic option on reconciler

CHANGELOG.md, DEVELOPMENT.md, README.md, docs/spec/v1beta2/kustomization.md
Signed-off-by: Daniel Holbach <daniel@weave.works>
=> update to new doc links structure

controllers/kustomization_controller.go, controllers/kustomization_wait_test.go
=> Fix health checking for global objects

controllers/kustomization_controller.go, controllers/kustomization_wait_test.go
=> Don't override the reconcile error on status patching

.github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/scan.yml
Part of https://github.com/fluxcd/flux2/issues/3663
=> build: update release workflow

.github/dependabot.yaml, .github/workflows/cifuzz.yaml, .github/workflows/e2e.yaml, .github/workflows/nightly.yml, .github/workflows/release.yml, .github/workflows/scan.yml
Part of https://github.com/fluxcd/flux2/issues/3709
=> build: update `actions/setup-go` in workflows

internal/controller/kustomization_acl_test.go, internal/controller/kustomization_controller.go, internal/controller/kustomization_decryptor_test.go, internal/controller/kustomization_dependson_test.go, internal/controller/kustomization_fetcher_test.go, internal/controller/kustomization_force_test.go, internal/controller/kustomization_fuzzer_test.go, internal/controller/kustomization_impersonation_test.go, internal/controller/kustomization_indexers.go, internal/controller/kustomization_inventory_test.go, internal/controller/kustomization_prune_test.go, internal/controller/kustomization_transformer_test.go, internal/controller/kustomization_validation_test.go, internal/controller/kustomization_varsub_test.go, internal/controller/kustomization_wait_test.go, internal/controller/source_predicate.go, internal/controller/suite_test.go, internal/controller/utils.go, main.go
Keep pkg name in sync with dir.
=> Rename `controllers` to `controller`

.github/workflows/backport.yaml
Use fluxcdbot for backport PRs so it can run e2e tests.
=> Run backport workflow as fluxcdbot

internal/controller/kustomization_controller.go, internal/controller/utils.go
=> Exclude skipped resources from apply events

.github/workflows/backport.yaml
=> [release/v1.0.x] Manual backport of CI fixes

CHANGELOG.md
cherry picked from commit 28e1dc85c12eef22dda3562dc97b86b66f8bcaf8
=> Add changelog entry for v1.1.1

docs/spec/v1/README.md, docs/spec/v1alpha1/README.md, docs/spec/v1beta1/README.md, docs/spec/v1beta2/README.md
fixing 44 broken links in docs and correcting a title
=> Fix broken links in API docs

go.mod, go.sum
Includes trimming status condition messages, fix: https://github.com/fluxcd/flux2/issues/4470
=> Update runtime to v0.43.3

CHANGELOG.md
(cherry picked from commit e5072d57c60556a3fff875bb5004d64855071f95)
=> Add changelog entry for v1.2.2

Makefile, config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
Part of: https://github.com/fluxcd/flux2/issues/4947
=> Update controller-gen to v0.16.1

internal/decryptor/decryptor.go, internal/decryptor/decryptor_test.go
=> Fix secret value showing up in logs

internal/controller/kustomization_controller.go
=> Fix performance regression due to using client without cache

docs/spec/v1/kustomizations.md
Part of: https://github.com/fluxcd/flux2/issues/5022
=> [RFC-0010] Link workload identity docs to complete guide

.github/dependabot.yaml
Part of: https://github.com/fluxcd/flux2/issues/5372
=> Update dependabot config

go.mod, go.sum
Depends on: https://github.com/fluxcd/pkg/pull/988
Part of: https://github.com/fluxcd/flux2/issues/5022
=> [RFC-0010] Support all Azure clouds for remote clusters at the controller level

CHANGELOG.md, config/manager/kustomization.yaml, go.mod
Part of: https://github.com/fluxcd/flux2/issues/5516
=> Release v1.7.0
