README.md
api/v1alpha1/kustomization_types.go
config/crd/bases/kustomize.fluxcd.io_kustomizations.yaml
controllers/kustomization_controller.go
controllers/kustomization_predicate.go

Changes:
- add `GarbageCollect` predicate to `KustomizationReconciler`
- remove the Kubernetes objects previously applied on the cluster, based on `spec.prune` label select
- add garbage collection spec to docs

Implement garbage collection

---

api/v1alpha1/kustomization_types.go
config/crd/bases/kustomize.fluxcd.io_kustomizations.yaml
controllers/kustomization_controller.go
docs/spec/README.md
docs/spec/v1alpha1/README.md
docs/spec/v1alpha1/kustomization.md

- add `LastAppliedRevision` field to Status sub-resource
- set `status.LastAppliedRevision` after a successful sync
- add Status section to spec docs

Record last applied revision

---

api/v1alpha1/condition_types.go
api/v1alpha1/kustomization_types.go
controllers/kustomization_controller.go

Set ready condition to unknown while the reconciliation is progressing.
This allows other operators to wait for a sync to complete e.g:
```
kubectl annotate --overwrite kustomization/podinfo kustomize.fluxcd.io/syncAt="$(date +%s)" && \
kubectl wait kustomization/podinfo --for=condition=ready --timeout=1m
```

Report progressing status

---

config/manager/deployment.yaml
controllers/kustomization_controller.go
main.go

Make the controller watch for resources only in namespace where it has been deployed.

Watch resources in the runtime namespace only

---

controllers/kustomization_controller.go

When a release is marked as suspended no operations should be performed
for the release except acknowledging the reconciler has noticed it has
been suspended. This means the suspend check should happen _before_ the
Kustomization is marked as progressing (which should be an indicator
reconciliation is enabled for the Kustomization).

Check suspend status before progressing

---

Dockerfile

Fixes JSON patch exponential time complexity for nesting depth of manifest https://github.com/kubernetes/kubernetes/issues/91615

Update kubectl to v1.18.8

---

api/v1alpha1/sort.go
docs/api/kustomize.md

As this better reflects the error's contents.
Aligns with changes made in https://github.com/fluxcd/helm-controller/pull/58.

api: rename Unsortable to CircularDependencyError

---

config/manager/deployment.yaml
main.go

This change should be mode for all controllers as the debug level is too verbose when issuing Kubernetes events.

Configure manager logging and set level to info

---

api/v1alpha1/snapshot_types.go
controllers/kustomization_controller.go
controllers/kustomization_gc.go

Changes:
- rewrite GC with controller-runtime client instead of kubectl shell-outs
- track group version kinds instead of kinds (GC snapshot API breaking change)
- ignore objects that are no longer present on the cluster
- delete namespaced CRs before CRDs
- mark for deletion objects with finalizers
- ignore objects stuck in finalization
Fix: #98

Refactor garbage collector

---

controllers/kustomization_controller.go

Set kubectl cache-dir to /tmp to avoid throttling due to readonly rootfs.

Set kubectl cache dir to /tmp

---

Makefile
api/v1alpha1/snapshot_types.go
config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
controllers/kustomization_controller.go
controllers/kustomization_gc.go
controllers/kustomization_generator.go
docs/api/kustomize.md

This PR changes the way GC tracks changes, instead of labeling the Kubernetes objects with the source revision, we calculate the checksum of the manifests included in a kustomization and we use the checksum to label the applied objects. 
The GC labels have changed to:
```
kind: Namespace
metadata:
labels:
kustomize.toolkit.fluxcd.io/checksum: b3bd93b79387fa664600bdc82c6a8ee54932a95c
kustomize.toolkit.fluxcd.io/name: test
kustomize.toolkit.fluxcd.io/namespace: gitops-system
name: dev
```
The name and namespace labels can be used to list all objects belonging to a kustomization:
```
$ kubectl get deployments \
-l=kustomize.toolkit.fluxcd.io/name=test,kustomize.toolkit.fluxcd.io/namespace=gitops-system \
--all-namespaces 
NAMESPACE   NAME       READY   UP-TO-DATE   AVAILABLE   AGE
dev …
```

Use manifests checksum in GC snapshot

---

README.md
api/v1alpha1/condition_types.go
api/v1alpha1/kustomization_types.go
controllers/kustomization_controller.go
controllers/kustomization_controller_test.go
docs/internal/release.md
docs/spec/README.md
docs/spec/v1alpha1/README.md
docs/spec/v1alpha1/kustomization.md

Changes:
- use reconciliation instead of apply for condition reasons
- add the reconciliation errors to the condition message
- trim the condition message to 4000 characters
- update the API docs and readme with the new condition reasons
- add the API package to release docs

Normalize the ready condition reasons

---

.github/workflows/release.yml

Fail build if container images have been pushed with corrupted layers and enable buildx debug logs, ref: https://github.com/fluxcd/toolkit/issues/241
PS. This needs to be ported on all the toolkit controllers

ci: Add sanity check for container images

---

api/v1alpha1/kustomization_types.go
config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
controllers/kustomization_generator.go
docs/api/kustomize.md
docs/spec/v1alpha1/kustomization.md

Changes:
- Add `TargetNamespace` field to API and docs
- Implement namespace overriding
This PR allows setting or overriding the namespace in the` kustomization.yaml`, making possible for cluster admins to onboard external apps into existing namespaces. This will also open the path to create ephemeral namespaces for PR reviews.

Implement namespace overriding

---

api/v1alpha1/kustomization_types.go
config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
controllers/kustomization_controller.go
docs/api/kustomize.md
docs/spec/v1alpha1/kustomization.md

This makes it possible for e.g. the GOTK CLI to observe if the controller has handled the resource since the manual reconciliation request was made.
Ref: https://github.com/fluxcd/toolkit/discussions/217

Record last handled reconcile at annotation

---

docs/spec/v1beta1/kustomization.md

Add a notice regarding using health checks with Helm charts containing a single replica.
This notice should be removed when https://github.com/helm/helm/pull/8671 is merged.
Fixes https://github.com/fluxcd/helm-controller/issues/81

Update health check docs

---

Makefile
config/default/kustomization.yaml
controllers/kustomization_controller.go

When the source is not found the status wasn't updated accordingly.

Fix status reporting when the source is not found

---

controllers/kustomization_generator.go

Changes:
* take into account only .yaml and .yml files when creating the resource list for the `kustomization.yaml` file
* validate that yaml files are Kubernetes objects and stop the reconciliation if the validation fails
Fix: #142

Validate manifests when generating kustomization.yaml

---

api/go.mod
api/go.sum
api/v1beta1/kustomization_types.go
api/v1beta1/zz_generated.deepcopy.go
config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
controllers/bucket_watcher.go
controllers/gitrepository_watcher.go
controllers/kustomization_controller.go
controllers/kustomization_request.go
docs/api/kustomize.md
go.mod
go.sum
hack/api-docs/config.json

Per https://github.com/fluxcd/pkg/issues/39.

Use annotation helpers

---

controllers/kustomization_controller.go

When no Kubernetes resources are created or configured for a `Kustomization` and it has no dependencies, the health check status for the `Kustomization` will not change.
In this case kustomize-controller does not have to deliver health check events.
What do you think?

Suppress health check events when no changes made

---

config/rbac/role.yaml
controllers/kustomization_controller.go

Shaved off a bit too much in #153.

Log reconciliation requests by watcher

---

controllers/kustomization_controller.go

To avoid stale status writes, we use the latest object generation before updating the final status sub-resource.

Use latest generation when updating final status

---

api/v1beta1/kustomization_types.go
config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
controllers/kustomization_controller.go
docs/api/kustomize.md
docs/spec/v1beta1/kustomization.md

This PR adds `none` to the list of accepted values for `spec.validation`, this allows users to explicitly disable the dry-run apply.

Allow disabling validation

---

controllers/kustomization_controller.go

This PR replaces status updates with patches to avoid  "the object has been modified; please apply your changes to the latest version and try again".

Patch status sub-resource

---

docs/spec/v1beta1/kustomization.md

Add docs for excluding non-k8 YAML files in kustomization generation

---

CHANGELOG.md
config/manager/kustomization.yaml
go.mod

This is the third MINOR prerelease. It introduces two breaking changes:
* the `ServiceAccount` field has been removed and replaced by `ServiceAccountName`; it is no longer possible to specify a namespace for a service account, the namespace is inferred from the Kustomization namespace 
* the status condition type has changed to the type introduced in Kubernetes API machinery `v1.19.0`

Release v0.3.0

---

controllers/kustomization_controller.go

In case the artifact watcher doesn't receive the source update event, we should requeue based on the specfied interval to avoid a forever stuck Kustomization.

Requeue after interval on source not found errors

---

controllers/kustomization_controller.go

This would allows to have more details when using the [kubectl blame](https://github.com/knight42/kubectl-blame) plugin.
At the moment a deployment managed by kustomize would look like this:
<details><summary>CLICK ME</summary><p>
```
apiVersion: apps/v1
kind: Deployment
metadata:
kubectl-client-side-apply (Update 2020-11-18 14:07:18 +0100)   annotations:
kube-controller-manager   (Update 2020-11-18 14:07:18 +0100)     deployment.kubernetes.io/revision: "1"
kubectl-client-side-apply (Update 2020-11-18 14:07:18 +0100)   labels:
kubectl-client-side-apply (Update 2020-11-18 14:07:18 +0100)     app: go-lev
kubectl-client-side-apply (Update 2020-11-18 14:07:18 +0100)     kustomize.toolkit.fluxcd.io/checksum: 1f9831532b54595a131456fd03a7e7ed0afb9b74
kubectl-client-side-apply (Update 2020-11-18 …
```

Set --field-manager when applying

---

MAINTAINERS

See https://github.com/fluxcd/flux2/discussions/515.

Share fluxcd/flux2 maintainers

---

api/v1beta1/kustomization_types.go
controllers/kustomization_controller.go
controllers/utils.go

Changes:
- filter kubectl apply output and extract errors
- limit apply output to 20K charts (avoid reaching max etcd size)
- log kubectl exit code when the process is killed
Fix: #167
Fix: #190
Fix: #202
Fix: #203

Refactor apply error reporting

---

api/v1beta1/kustomization_types.go
config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
controllers/kustomization_controller.go
controllers/kustomization_decryptor.go
docs/api/kustomize.md
docs/spec/v1alpha1/kustomization.md
docs/spec/v1beta1/kustomization.md
go.mod
go.sum

This commit ensures that relative (user configurable) paths never
traverse outside their working directory.
It does _not_ provide protection against path traversal within
`kustomization.yaml` files.

Make Path field optional and add safe guards for relative paths

---

controllers/kustomization_controller.go

Healthcheck can temporarily fail due to slow application startup, network failure, etc.
In this case, Flux emits an event of the failed healthcheck.
But when the healthcheck passes in another reconciliation, the current implementation does not emit a healthcheck event because the revision has not changed.
This PR fixes this behavior.
Flux will always emit a healthcheck event if a Kustomization was not ready in the previous reconciliation.

Emit healthcheck event when Kustomization was not ready

---

controllers/kustomization_generator.go

Fixes https://github.com/fluxcd/kustomize-controller/issues/223
Signed-off-by: Michał Flendrich <michal@flendrich.pro>
Before this PR, kustomize-controller (incorrectly) takes a directory named `Kustomization` as a kustomization file, with the following consequences:
- the directory which contains the directory called `Kustomization` is erroneously omitted from processing
- trying to open the `Kustomization` directory as a file results in an error, reported by kustomization-controller
After this PR, when traversing the filesystem tree looking for Kustomization files, kustomization-controller doesn't try to take directories as kustomization files.
Testing: I believe that this change deserves an e2e test case, but apparently, in the current shape of e2e tests, this requires a GitHub …

No longer treat dirs as kustomization files

---

main.go

If you have a lot of flux kustomizations you may face with getting stuck on reconciliation. Throttling errors is cause. You may increase QPS and Burst values and throttling go away

Add QPS and Burst kube api client parameters as CLI arguments

---

controllers/kustomization_generator.go

Fixes: #225 
Before this commit we only checked if a `kustomization.yaml` existed at
the root of the given directory, this caused problems when people for
example used `.yml` as the extension, as the generated
`kustomization.yaml` would conflict with the `.yml` file.
After this commit all recognized Kustomization filenames as listed by
Kustomize itself are accepted, including files _without_ an extension
(`Kustomization`).

Look for all accepted Kustomization filenames

---

Dockerfile
controllers/kustomization_controller.go
controllers/kustomization_generator.go
go.mod
go.sum

This PR updates `kustomize/api` to v0.7.2 and disables `kyaml` when running kustomize build due to upstream bugs:
- https://github.com/kubernetes-sigs/kustomize/issues/3446
- https://github.com/kubernetes-sigs/kustomize/issues/3480
Note that when `kyaml` is enabled, `Kustomizer.Run` fails with `Error: json: unsupported type: map[interface {}]interface {}` without any hint to which object caused the error, making it impossible for Flux users to track down the incompatible manifest.
Also if a manifest contains duplicate keys, kyaml panics thus crashing the whole controller 😢 
Fix: https://github.com/fluxcd/flux2/issues/729
Fix: #243

Update kustomize/api to v0.7.2 and disable kyaml

---

api/v1beta1/kustomization_types.go
api/v1beta1/zz_generated.deepcopy.go
config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
controllers/kustomization_controller.go
controllers/kustomization_controller_test.go
docs/api/kustomize.md
docs/spec/v1beta1/kustomization.md

This PR adds an optional field `spec.retryInterval ` to the API that allows users to requeue a failed reconciliation at a different interval than `spec.Interval`.
Changes:
- Add `RetryInterval` as optional field to API. The spec.retryInterval is the interval at which to retry a previously failed reconciliation. When not specified, it defaults to the `spec.interval` value.
- Requeue a failed reconciliation based on retry interval 
- Add reconciliation unit test to verify that objects are create in cluster and labeled accordingly
Fix: #246

Allow failed reconciliations to be scheduled at a different interval 

---

controllers/kustomization_controller.go

Reconciliation failures should be scheduled at the specified retry interval. Log the reconciliation error instead of returning it, so that controller-runtime doesn't requeue immediately. 
Followup: #250

Fix reconciliation retry scheduler

---

controllers/kustomization_impersonation.go

When running in a cluster, the BearerTokenFile is set to point to
`/var/run/secrets/kubernetes.io/serviceaccount/token` where the service
account's token is auto-mounted. If this value is not cleared, the
setting of the BearerToken field will have no effect. Relevant
documentation:
https://pkg.go.dev/k8s.io/client-go@v0.20.2/rest#Config.BearerTokenFile

impersonation: Clear config.BearerTokenFile when setting BearerToken.

---

controllers/kustomization_controller.go

Having a similar setup as in https://github.com/fluxcd/kustomize-controller/issues/217. Running kustomize-controller with minimal privileges and using `serviceAccountName` to "elevate" privileges for Kustomizations.
Kustomization validation was performed with the kustomize-controller service account, which with the above setup doesn't have the required privileges. This PR adds support for service account impersonation during validation.
Same approach as for apply(): https://github.com/splushii/kustomize-controller/blob/d0f2dc6e4aab2cd6dd454adec0698d5ea2bd644e/controllers/kustomization_controller.go#L595-L604

Support impersonation for validation

---

api/v1beta1/condition_types.go
api/v1beta1/kustomization_types.go
controllers/kustomization_controller.go
controllers/kustomization_controller_test.go

- record the last health assessment result in a dedicated status condition
- use the condition status when issuing events to prevent notifications spam (fix: #236)

Add Healthy status condition

---

README.md

When following the README, I noticed the `apiVersion` is slightly wrong. This commit adds `toolkit` to the alert and provider code blocks to allow people to copy and paste.

Add "toolkit" to the API reference in README

---

controllers/kustomization_gc.go
docs/spec/v1beta1/kustomization.md

This PR allows disabling pruning for certain resources by either labeling or annotating them with:
```yaml
kustomize.toolkit.fluxcd.io/prune: disabled
```
Fix: #237

Allow disabling of prune on certain resources

---

go.mod
go.sum

Note that we can't update the `kustomize/api` to [v0.8.0](https://github.com/kubernetes-sigs/kustomize/releases/tag/api%2Fv0.8.0) because it forces us into using `kustomize/kyaml`. The kyaml library has serious issues, for example the controller will crash loop with no option for recovery due to kyaml usage of `log.Fatal` 🤦  https://github.com/kubernetes-sigs/kustomize/issues/3480

Update kustomize/api to v0.7.4 (last version without kyaml)

---

CONTRIBUTING.md
controllers/kustomization_controller.go

This PR makes it possible to run kustomize-controller locally for debugging purposes against a test cluster.

Allow the controller to be run locally

---

controllers/kustomization_controller.go
controllers/utils.go
controllers/utils_test.go

An attempt to treat validation error output the same way as apply output: reducing the noise by only returning the validation error.
Fixes: #277
Note: I'm not sure about the BDD framework used in the project. Let me know if I misuse it

Extracting validation error from apply dry run output

---

controllers/kustomization_controller.go
go.mod
main.go

This PR implements retries with exponential backoff when fetching artifacts from source-controller. By default, the controller does 10 attempts within a 3.5 minutes window, the number of max retries can be configure using the `--http-retry` cmd arg.
This mitigates the alert spam (`i/o timeout err`) when source-controller becomes unavailable for a short period of time e.g. after an upgrade. 
Example error log:
```json
{"level":"error","ts":"2021-02-26T12:03:19.710+0200","logger":"controller.kustomization","msg":"Reconciliation failed after 3m35.317406763s, next try in 5m0s","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"podinfo","namespace":"flux-system","revision":"master/e43ebfa5bf4b87c46f2e1db495eb571cd398e2f7","error":"failed to download …
```

Retry with exponential backoff when fetching artifacts

---

controllers/kustomization_controller_test.go
controllers/kustomization_varsub.go
docs/spec/v1beta1/kustomization.md

The name of a variable used in post build substitutions can contain only alphanumeric and underscore characters. This PR implements validation for the variable names using `^[_[:alpha:]][_[:alpha:][:digit:]]*$` regex. 
Fix: #290

Validate the var names before substitution

---

controllers/kustomization_controller.go

Use the timeout set by the http client when retrying with exponential backoff, followup #289

Do not override the artifact fetch timeout

---

api/go.mod
api/go.sum
controllers/kustomization_controller.go
go.mod
go.sum

Part of [flux#590](https://github.com/fluxcd/flux2/issues/590)

Expose suspended status as Prometheus metric

---

api/go.mod
api/go.sum
go.mod
go.sum
main.go

This PR allows fine tuning the leader election with cmd args:
```
--enable-leader-election=true
--leader-election-release-on-cancel=true
--leader-election-lease-duration=35s
--leader-election-renew-deadline=30s
--leader-election-retry-period=5s
```
To make the leader election more tolerant to transient Kubernetes API outages, the renewal deadline was increased from 10s to 30s and the retry interval was bumped to 5 seconds.
Part of: https://github.com/fluxcd/pkg/issues/94

Set leader election deadline to 30s

---

controllers/kustomization_controller.go
controllers/kustomization_controller_sops_test.go

This should give users some guidance when `kubectl apply` itself does
not give any useful output back itself, till date only observed when
it times out waiting.
Should help some with #311.

Detect and replace empty err output on apply

---

controllers/kustomization_controller.go

Reduce the log level from error to info to match the level of the event.  The `kustomize-controller` pod's log has `error` message like:
`{"level":"error","ts":"2021-03-26T02:39:43.980Z","logger":"controller.kustomization","msg":"Dependencies do not meet ready condition, retrying in 30s","reconciler group":"kustomize.toolkit.fluxcd.io","reconciler kind":"Kustomization","name":"apps","namespace":"flux-system","error":"dependency 'flux-system/infrastructure' is not ready"}`
though the events / notifications written are at level `info`.
Context is discussion at https://github.com/fluxcd/flux2/discussions/1160#discussioncomment-580148

Make log level info for 'Dependencies do not meet ready condition'

---

controllers/kustomization_controller.go
controllers/kustomization_indexers.go

This PR refactored indexers by using high-order functions to replace redundant codes by half without altering the semantics.

Refactor indexers to use high-order functions

---

controllers/utils.go
controllers/utils_test.go

In addition to client dry-run, I also improve the server dry-run case to reduce verbose output and only print errors.
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
$ kubectl create deploy nginx --image nginx --dry-run=client -o yaml | kubectl apply -f- --dry-run=server
deployment.apps/nginx created (server dry run)
```
ref/ …

Extracting validation error from apply server dry run output

---

controllers/kustomization_controller.go

`err` returned from `command.CombinedOutput()` is an error of the command execution, not an error of the context.
To determine if the context was canceled, we should check out `context.Err()`.
Signed-off-by: Hidehito Yabuuchi <hdht.ybuc@gmail.com>

Fix validation and application timeout handling

---

controllers/kustomization_controller_sops_test.go
controllers/kustomization_decryptor.go
controllers/testdata/sops/.sops.yaml
controllers/testdata/sops/month/kustomization.yaml
controllers/testdata/sops/month/month.yaml

This is an extension of #329, which added the support for decrypting files passed to the secret generator. The previous implementation only supported encrypted binary types, but failed when the content was a JSON or a YAML, with the message `EmitPlainFile: No binary data found in tree`.
This small change detects the format using the key/filename in the secret.

Support decrypting any file format in secret generator

---

CONTRIBUTING.md
controllers/kustomization_controller_gc_test.go
controllers/kustomization_controller_test.go
controllers/kustomization_gc.go
controllers/kustomization_generator.go

This PR moves the `kustomize.toolkit.fluxcd.io/checksum` from labels to annotations. This should fix any conflicts with 3rd party controllers like Stash (fix: #315) that are copying the labels from their custom resources to generated objects.

Move the GC checksum from labels to annotations

---

api/go.mod
api/go.sum
api/v1beta1/kustomization_types.go
api/v1beta1/zz_generated.deepcopy.go
config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
controllers/kustomization_controller_patch_test.go
controllers/kustomization_generator.go
docs/api/kustomize.md
docs/spec/v1beta1/kustomization.md
go.mod
go.sum

The `patchesJson6902` or `patchesStrategicMerge` fields in a Kustomize resource only allow patching single named resources. In order to patch multiple resources with a single patch, the generic `patches` field need to be used.
This PR implement the generic `patches` at the kustomize.toolkit.fluxcd.io/v1beta1/Kustomization level to unlock that feature.
One use case, would be for instance to override all path of all Kustomization at once without having to patch then one by one:
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
name: podinfo
namespace: flux-system
spec:
patches:
- patch: |-
- op: replace
path: /spec/path
value: ./deploy/lab/
target:
group: kustomize.toolkit.fluxcd.io
version: v1beta1
kind: Kustomization
```
The field `options` from the …

Add support for in-line generic patches to Flux Kustomization API

---

CHANGELOG.md

Missed the drop of the YAML anchors support from Kustomize v4.

Add YAML anchors to breaking changes

---

controllers/kustomization_healthcheck.go

Whenever a health check times out now, the most recently collected error for each resource will be printed as part of the error message. This excludes errors for those resources for which no error was reported in the last update. This is because whenever a timeout occurs, an error is reported on ALL resources, even those that have been seen as healthy before.
Also, this commit causes all successfully checked resources to be omitted in the error event.
This is how it will look in the API:
Before:
```
$ k -n flux-system get events --field-selector=involvedObject.kind=Kustomization -w
LAST SEEN   TYPE     REASON   OBJECT                MESSAGE
34m         Normal   info     kustomization/test1   configmap/test1 created
32m         Normal   info     kustomization/test1   Update completed
0s …
```

feat: make it easier to reason about health check failures

---

go.mod
go.sum

Changes:
- sigs.k8s.io/kustomize/api [v0.8.11](https://github.com/kubernetes-sigs/kustomize/releases/tag/kyaml%2Fv0.11.0)
- sigs.k8s.io/kustomize/kyaml [v0.11.0](https://github.com/kubernetes-sigs/kustomize/releases/tag/api%2Fv0.8.11)
For more details see kustomize v4.2.0 [changelog](https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv4.2.0).

Update controller to kustomize v4.2.0

---

docs/spec/v1beta1/kustomization.md

Signed-off-by: Oliver Bähler <oliverbaehler@hotmail.com>
Documents that var substitution must have set at least one var the be executed. Fixes #388

Var substitution opt-in docs

---

controllers/kustomization_healthcheck.go

The `lastStatus` map now stores `event.ResourceStatus` values instead
of pointers to them, preventing nil pointers being dereferenced by
accident.
refs https://github.com/fluxcd/kustomize-controller/pull/374
Signed-off-by: Max Jonas Werner <mail@makk.es>

fix: prevent nil pointer dereference in health checks

---

controllers/kustomization_controller_test.go
controllers/kustomization_impersonation.go
docs/spec/v1beta1/kustomization.md

Add `values.yaml` to the supported kubeconfig secret key names in order for SOPS to correctly detect the storage format based on the file extension.
Fix: #399 
~~TODO: This must be ported to helm-controller before the next flux release.~~

Make the kubeconfig secrets compatible with SOPS

---

controllers/kustomization_controller.go
controllers/utils.go
controllers/utils_test.go

Different approach to fix #419

Mask the Kubernetes Secrets data from dry-run and apply logs

---

go.mod
go.sum
internal/sops/pgp/keysource.go

Remove gopass dependency 

---

controllers/kustomization_controller.go
go.mod
go.sum

Set delete propagation policy to background

---

controllers/kustomization_controller.go
controllers/kustomization_decryptor.go

If decryption is not enabled, SOPS encrypted secrets will fail to apply with a validation error that doesn't give any hints. It's better to exit early and throw an error that tells users to enable decryption.

Warn when secrets are not decrypted before apply

---

Makefile
config/default/kustomization.yaml
controllers/kustomization_controller.go
controllers/kustomization_decryptor_test.go
controllers/kustomization_dependson_test.go
controllers/kustomization_force_test.go
controllers/kustomization_inventory_test.go
controllers/kustomization_prune_test.go
controllers/kustomization_transformer_test.go
controllers/kustomization_varsub_test.go
controllers/kustomization_wait_test.go
controllers/suite_test.go
go.mod
go.sum

After downloading an artifact, compute its checksum and verify that it matches the original checksum as advertised by source-controller.
For backwards compatibility with source-controller v0.17.2, the checksum is computed with SHA1, on clusters with a newer source-controller we use SHA256.
Addresses https://github.com/fluxcd/source-controller/issues/468

Verify artifacts integrity

---

controllers/kustomization_controller.go
controllers/kustomization_force_test.go
controllers/kustomization_generator.go
controllers/kustomization_impersonation.go
controllers/kustomization_indexers.go
controllers/kustomization_prune_test.go
controllers/kustomization_transformer_test.go
controllers/kustomization_varsub_test.go
go.mod
go.sum
internal/sops/keyservice/server.go
internal/sops/pgp/keysource.go

This PR contains various small fixes reported by [staticcheck](https://staticcheck.io/) and replaces the following deprecated packages:
- `sigs.k8s.io/kustomize/api/filesys` -> `sigs.k8s.io/kustomize/kyaml/filesys`
- `google.golang.org/grpc` -> `google.golang.org/grpc/status`
- `golang.org/x/crypto/openpgp` -> `github.com/ProtonMail/go-crypto/openpgp`
- `golang.org/x/crypto/openpgp/armor` -> `github.com/ProtonMail/go-crypto/openpgp/armor`

Replace deprecated dependencies

---

controllers/kustomization_varsub_test.go
docs/spec/v1beta2/kustomization.md

Add test for varsub in secret

---

docs/spec/v1beta2/kustomization.md

Closes https://github.com/fluxcd/flux2/issues/2099

Document behaviour when changes are made to fields not stored in git 

---

internal/sops/keyservice/server.go

make sure we use the right service to encrypt.

sops: ensure proper wiring to default server

---

controllers/kustomization_controller.go

Add check for nil to fix inconsistent code-style raised at the security audit.
Relates to https://github.com/fluxcd/pkg/issues/173

Fix inconsistent code-style raised at security audit

---

go.mod
go.sum

Update fluxcd/pkg/ssa to v0.8.0 that implements a [workaround](https://github.com/fluxcd/pkg/pull/207) for a Kubernetes API server-side apply dry-run bug where the HPA custom metrics are duplicated.
Fix: #494

Fix HPA diff (upstream bug)

---

controllers/kustomization_controller.go

As discussed in https://cloud-native.slack.com/archives/CLAJ40HV3/p1639665724208200 we identified a race condition in checkDependencies when using Receiver and both Kustomizations have the same SourceRef. 
If triggered by the Receiver the checkDependencies is executed before the dependent Kustomization applied the latest Revision. To prevent this we check if the LastAppliedRevision is already the new Revision.
In this Case deployment-demoapp has an dependsOn to init-demoapp. This time deployment-demoapp waits untils init-demoapp applied the latest Revision:

Add condition to checkDependencies when SourceRef is the same

---

Makefile

Ref: https://github.com/fluxcd/flux2/issues/2273

Use go install instead of go get in Makefile

---

docs/spec/v1beta2/kustomization.md

Describe explicitly in docs how to escape variable substitution operator when you need to keep the dollar sign and curly braces.
Closes: https://github.com/fluxcd/website/issues/705

Docs - Add var substitution operator escape syntax

---

controllers/kustomization_controller.go
controllers/kustomization_decryptor_test.go
controllers/kustomization_validation_test.go
controllers/testdata/invalid/overlay/deployment.yaml
controllers/testdata/invalid/overlay/kustomization.yaml
controllers/testdata/invalid/plain/deployment.yaml
go.mod
go.sum

Validate that the resources built with kustomize conform to the Kubernetes API conventions before passing them to the server-side apply engine.
Fix: #542

Fix preflight validation

---

api/go.mod
api/go.sum
controllers/kustomization_acl_test.go
controllers/kustomization_controller.go
controllers/suite_test.go
docs/spec/v1beta2/kustomization.md
go.mod
go.sum
main.go

Introduce the flag `--no-cross-namespace-refs` (defaults to false) for allowing cluster admins to disable cross-namespace references to sources.
When the controller is run with `--no-cross-namespace-refs=true` and a `Kustomization.spec.sourceRef.namespace` refers to a `GitRepository` or `Bucket` in a different namespace than the `Kustomization` object, the reconciliation will fail with the `AccessDenied` reason.
On access denied errors the controller logs and sends an event e.g.:
```
can't access 'GitRepository/my-other-namespace/my-source', cross-namespace references have been blocked
```
And the `Kustomization` status `Ready` condition it set to:
```yaml
status:
conditions:
- lastTransitionTime: "2022-01-26T07:26:48Z"
message: "can't access 'GitRepository/my-other-namespace/my-source', …
```

Allow disabling cross-namespace references

---

controllers/kustomization_controller.go
controllers/kustomization_impersonation.go
controllers/kustomization_impersonation_test.go
docs/spec/v1beta2/kustomization.md
main.go

Introduce the flag `--default-service-account` for allowing cluster admins to enforce impersonation across the cluster without having to use an admission controller. 
When the flag is set to a value that's not empty string, all Kustomizations which don't have `spec.serviceAccountName` specified, they will use the service account name provided by `--default-service-account=<SA Name>` in the namespace of the object.
**Breaking changes**: 
- When `--default-service-account=<SA name>` and/or `spec.ServiceAccountName` are specified, the controller no longer queries the API to extract and use the SA token. Instead, the controller relies on the Kubernetes impersonation feature to run the reconciliation under the `system:serviceaccount:<SA Namespace>:<SA Name>` identity. This impacts only …

Allow setting a default service account for impersonation

---

.github/workflows/e2e.yaml
config/testdata/managed-fields/podinfo.yaml
controllers/kustomization_controller.go
go.mod
go.sum

This PR enforces Flux ownership of Kubernetes objects' fields that were applied on the cluster outside of the declared desired state. In addition, metadata annotations and labels removed from Git and are now removed from the cluster.
In order to undo changes made with `kubectl apply -f` and `kubectl apply --server-side --force-conflicts`, we have to replace `kubectl-*` managers with our own manager before the controller runs the server-side apply. 
In addition, this PR removes the kubectl last applied configuration annotation and Flux v1 & v2 deprecated metadata. 
References: 
- Fix: https://github.com/fluxcd/kustomize-controller/issues/486
- Fix: https://github.com/fluxcd/flux2/issues/2262
- Fix: #545 
- Followup: #426
Upstream bugs:
- …

Revoke kubectl managed fields ownership

---

controllers/kustomization_controller.go
controllers/kustomization_impersonation.go
controllers/kustomization_impersonation_test.go

If the service account used for impersonation has been deleted, skip pruning, log the error and continue with finalization to allow tenants removals from clusters.
Followup: #550

Ensure object are finalized under impersonation

---

go.mod
go.sum

Instead of replacing kubectl managers with `kustomize-controller`, we are now merging the kubectl managed fields under the `kustomize-controller` manager. This ensures no fields are left without a manager even if some fields were remove from source.
Fix: #558

Transfer ownership of the kubectl managed fields

---

docs/spec/v1beta2/kustomization.md

Fixes fluxcd/flux2#2357 - Docs accessibility
It's clear what was intended here if you know that Flux Kustomization has `spec.path` and GitRepository doesn't have any such a field, but that's presumptive about the user's knowledge. Let's not assume they've already learned and retained that.

Clarify spec.path in API docs

---

go.mod
go.sum

Update `sigs.k8s.io/kustomize/api` to v0.11.2
Fix regression: Support for pseudo git HTTP urls in the git cloner had broken in 59c82659 (https://github.com/kubernetes-sigs/kustomize/pull/4453)

Update controller to kustomize v4.5.2

---

api/v1beta2/kustomization_types.go
config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
controllers/kustomization_varsub.go
controllers/kustomization_varsub_test.go
controllers/suite_test.go
docs/api/kustomize.md
docs/spec/v1beta2/kustomization.md

In a _Kustomization_'s post-build substitution sources, introduce a new "Optional" field to allow referencing a Kubernetes _ConfigMap_ or _Secret_ that may not exist at time of reconciliation. Treat substitution when the referenced object is missing as if the object had been present but empty, lacking any variable bindings.
Retain the longstanding behavior of interpreting references to Kubernetes objects being mandatory by default, such that reconciliation fails if such a referenced object does not exist. Only when the "Optional" field is set to true will reconciliation tolerate finding the referenced object to be missing.
Fixes #565.

Tolerate absence of resources in post-build substitution

---

tests/fuzz/oss_fuzz_build.sh

Fixes issues building fuzzers whilst also ensuring that they are linking back to current version of kustomizer-controller and ./api.

Use main go.mod for fuzz tests

---

api/v1beta2/kustomization_types.go
config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml

Status content could be very long compare to other fields. Moving it to
the end helps improve the visibility of other fields.
Ref: https://github.com/fluxcd/flux2/issues/2385

api: Move Status in CRD printcolumn to the end

---

controllers/kustomization_controller.go
go.mod

This to facilitate improvements on the notification-controller side,
where annotations prefixed with the FQDN of the Group of the Involved
Object will be transformed into "fields".

Ensure annotations are prefixed with Group FQDN

---

.github/workflows/e2e.yaml
Makefile
config/default/kustomization.yaml
controllers/kustomization_decryptor.go
internal/sops/keyservice/server.go

(AMD64) image for testing available at: `hiddeco/kustomize-controller:fix-azkv-fallback-dc5486f`
Potentially addresses: https://github.com/fluxcd/kustomize-controller/issues/595

sops/keyservice: properly fallback to default

---

.github/workflows/e2e.yaml
Makefile
internal/sops/azkv/keysource.go
internal/sops/azkv/keysource_integration_test.go

```console
=== RUN   TestMasterKey_Encrypt
--- PASS: TestMasterKey_Encrypt (1.35s)
=== RUN   TestMasterKey_Decrypt
--- PASS: TestMasterKey_Decrypt (0.34s)
=== RUN   TestMasterKey_EncryptDecrypt_RoundTrip
--- PASS: TestMasterKey_EncryptDecrypt_RoundTrip (0.53s)
=== RUN   TestMasterKey_Encrypt_SOPS_Compat
--- PASS: TestMasterKey_Encrypt_SOPS_Compat (1.00s)
=== RUN   TestMasterKey_Decrypt_SOPS_Compat
--- PASS: TestMasterKey_Decrypt_SOPS_Compat (0.59s)
```
From: https://github.com/fluxcd/kustomize-controller/runs/5735891476
Ref: https://github.com/fluxcd/kustomize-controller/issues/595

sops/azkv: ensure compatibility with upstream

---

.github/workflows/e2e.yaml
DEVELOPMENT.md
Makefile
controllers/kustomization_controller.go
controllers/kustomization_impersonation.go
go.mod
go.sum
internal/sops/azkv/keysource_integration_test.go
main.go

Two new flags were added to allow users to enable the use of user.Exec (`--insecure-kubeconfig-exec`) and InsecureTLS (`insecure-kubeconfig-tls`) in the kubeconfigs provided for remote apply.
Breaking change: both functionalities are no longer enabled by default.

Add kubeconfig flags

---

internal/statusreaders/job.go
internal/statusreaders/job_test.go
main.go

This PR enables the controller to wait for Kubernetes Jobs to complete when `spec.wait` is set to `true`.
Fix: #553 

Implement health check for Kubernetes jobs

---

controllers/kustomization_controller.go
controllers/kustomization_decryptor.go
controllers/kustomization_decryptor_test.go

- Refactored recursion while iterating over Kustomization files.
References of files that have been visited are cached, and not
visited again.
- Optimized various bits around (un)marshalling (encrypted) data, and
YAML -> JSON -> YAML roundtrips are prevented where not required.
- Added support for decrypting INI Kustomize EnvSource references using
the dedicated SOPS store for the format.
- Introduced support for decrypting Kustomize FileSources:
https://pkg.go.dev/sigs.k8s.io/kustomize@v1.0.2/pkg/types#DataSources

controllers: improve decryptor and add tests

---

controllers/kustomization_controller.go
controllers/kustomization_generator.go
controllers/kustomization_generator_test.go
controllers/testdata/remote/kustomization.yaml
go.mod
go.sum

Depends on https://github.com/fluxcd/pkg/pull/264

generator: ensure remote build dirs can be reached

---

controllers/kustomization_controller.go
controllers/utils.go

Ensure generated temp dir is absolute on all OSes

---

controllers/kustomization_decryptor.go
controllers/kustomization_decryptor_test.go
controllers/suite_test.go

Rather than inspecting the source file name supplied to [_kustomize_'s _Secret_ generator](https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/secretgenerator/) to determine the format of the SOPS-encrypted file content, instead inspect the _Secret_ key—when supplied separately from the source file name—as a more reliable heuristic.
Doing so allows _kustomization_ authors to name their SOPS-encrypted output files with a ".json" extension accurately reflecting the format in which SOPS writes its encrypted output, even if the encrypted content itself is not in JSON format.
See [preceding discussion in the "flux" channel](https://cloud-native.slack.com/archives/CLAJ40HV3/p1650920860479349) of the CNCF Slack workspace for the circuitous path I took to diagnose this change in …

Use Secret generator keys for SOPS format hint

---

controllers/kustomization_generator.go
controllers/kustomization_generator_test.go
controllers/testdata/panic/kustomization.yaml
controllers/testdata/panic/secret.age.yaml

Kustomize tends to panic in unpredicted ways due to (accidental) invalid object data; recover when this happens to ensure continuity of operations.

generator: recover from kustomize build panics

---

api/go.mod
api/go.sum
api/v1beta2/kustomization_types.go
config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
controllers/kustomization_acl_test.go
controllers/kustomization_decryptor_test.go
controllers/kustomization_dependson_test.go
controllers/kustomization_force_test.go
controllers/kustomization_impersonation.go
controllers/kustomization_impersonation_test.go
controllers/kustomization_inventory_test.go
controllers/kustomization_prune_test.go
controllers/kustomization_transformer_test.go
controllers/kustomization_validation_test.go
controllers/kustomization_varsub_test.go
controllers/kustomization_wait_test.go
docs/api/kustomize.md
go.mod
go.sum
tests/fuzz/controllers_fuzzer.go

Support defining a KubeConfig Secret data key

---

controllers/kustomization_controller.go
controllers/kustomization_generator.go
controllers/kustomization_generator_test.go
docs/spec/v1beta2/kustomization.md
main.go

Add an optional flag for disabling Kustomize [remote bases](https://github.com/kubernetes-sigs/kustomize/blob/a7f4db7fb41e17b2c826a524f545e6174b4dc6ac/examples/remoteBuild.md).
While the `--no-remote-bases` is set to `false` by default, Flux users are encouraged to enable it on production system for security and performance reasons. Using Kustomize remote bases means that kustomize-controller must clone the remote repositories on every reconciliation instead of using the source-controller artifacts cache. Allowing remote bases on multi-tenant clusters, means platform admins have no control over which repositories make up the desired state. When this flag is enabled, all resources must refer to local files included in the source artifact, meaning that only the Flux sources defined in Git …

Disallow remote bases usage in Kustomize overlays

---

internal/sops/age/keysource.go
internal/sops/age/keysource_test.go
internal/sops/azkv/config.go
internal/sops/azkv/config_test.go
internal/sops/azkv/keysource.go
internal/sops/azkv/keysource_integration_test.go
internal/sops/azkv/keysource_test.go
internal/sops/hcvault/keysource.go
internal/sops/hcvault/keysource_test.go
internal/sops/keyservice/options.go
internal/sops/keyservice/server.go
internal/sops/keyservice/server_test.go
internal/sops/keyservice/utils_test.go
internal/sops/pgp/keysource.go
internal/sops/pgp/keysource_test.go

This relicenses all of our SOPS implementation code to MPL 2.0, where
Apache 2.0 was previously used due to code being written from scratch.
By making this license change, [we are better capable of contributing the
changes upstream](https://github.com/mozilla/sops/pull/1054#discussion_r877508185), which is in our best interest.
In case there is doubt about validity of DCO sign-off to make such
changes: all code where Apache 2.0 license applies were authored by
myself. In addition, Apache 2.0 is compatible with MPL 2.0 ([1][], [2][]).
[1]: https://opensource.com/law/11/9/mpl-20-copyleft-and-license-compatibility
[2]: https://blog.gerv.net/2013/02/relicensing-when-do-you-have-to-ask/
---
According to governance, this [requires voting](https://github.com/fluxcd/community/blob/main/GOVERNANCE. …

Relicense SOPS module to MPL 2.0

---

internal/sops/awskms/keysource.go
internal/sops/awskms/keysource_test.go

This PR is a follow up to #641 which fixes a few things around AWS KMS config creation and expands related tests.

sops/awskms: Fix AWS KMS config creation

---

config/default/kustomization.yaml
go.mod
go.sum

Update source-controller to v0.25.0 in e2e tests and bump the API package in go.mod.

Update source-controller/api to v0.25.0

---

controllers/kustomization_controller.go
controllers/kustomization_impersonation.go
main.go

Fixes: #686 
Use polling options (such as the internal custom job statusreaders) when creating a new status poller.

Fix job wait by adding polling options to impersonation client

---

controllers/kustomization_decryptor.go

Based on user reports, there seems to be a small chance for the
underlying SOPS store implementation to panic when a user provides input
and/or output format instructions which do not actually match the type
of the file. Recover from this to ensure continuity of operations.

decryptor: recover from SOPS store panic

---

.github/workflows/e2e.yaml
.gitignore
Makefile
api/v1beta2/reference_types.go
config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
config/default/kustomization.yaml
config/rbac/role.yaml
config/testdata/oci/podinfo.yaml
controllers/kustomization_controller.go
docs/spec/v1beta2/kustomization.md
go.mod
go.sum

This PR implements OCIRepository reconciliation as described in the RFC [Flux OCI support for Kubernetes manifests](https://github.com/fluxcd/flux2/tree/main/rfcs/0003-kubernetes-oci).
Changes:
- allow `OCIRepository` to be specified in `sourceRef.kind`
- react to `OCIRepository` artifacts events
- add end-to-end test for OCI repositories
- update source-controller API to v0.26.0
Depends on: 
- https://github.com/fluxcd/source-controller/pull/788
- https://github.com/fluxcd/flux2/pull/2856

[RFC-0003] Add support for OCIRepository sources

---

controllers/kustomization_decryptor.go

If one of the `kustomization.yaml` files can't be unmarshal by the SOPS decryptor, users can't tell from the error message which file was at fault e.g.
```
error decrypting env sources: failed to unmarshal kustomization file: error unmarshaling JSON: while decoding JSON: json: cannot unmarshal string into Go struct field Kustomization.patches of type types.Patch
```
This PR adds the file path to the error message.

Add file path to sops decryption errors

---

docs/spec/v1beta1/kustomization.md
docs/spec/v1beta2/kustomization.md

`targetNamespace` for a kustomization CRD is optional. The doc seemed slightly misleading, adding more details to clarify the doc.
Relevant discussion: https://cloud-native.slack.com/archives/CLAJ40HV3/p1661003204571329

Update doc on target namespace

---

controllers/kustomization_controller.go
controllers/kustomization_fetcher_test.go

This PR adds a new stage to the server-side apply where the controller reconciles the Kubernetes Class types (RuntimeClass, PriorityClass, StorageClass, VolumeSnapshotClass, IngressClass, GatewayClass, ClusterClass, etc) after CRDs, but before any other resource type. This allows users to bundle Class types with their consumers, e.g. ClusterClass and Cluster, or IngressClass and Ingress.
Fix: #719 
PS. This PR also fixes a flaky test.

Reconcile Kubernetes class type objects in a dedicated stage

---

.github/workflows/cifuzz.yaml
Makefile

General optimisations in preparation for converting to Go native fuzz:
- Ensures CI runs on Go 1.18.
- Fix caching path and reuse cache from host.
- Ensure latest oss-fuzz base images are being used.
Relates to https://github.com/fluxcd/flux2/issues/2417.

fuzz: Fuzz optimisations 

---

controllers/kustomization_decryptor.go
internal/sops/keyservice/keyservice.go

This is to sort master keys so PGP/age keys appear before the others and being used first. Thus if one of local methods is successful we avoid going to remote KMS/HCVault which may not be accessible from specific network and cause unnecessary timeouts or have some other cost.
Originally I've submitted [PR to SOPS project ](https://github.com/mozilla/sops/pull/1121) as solution for [this issue](https://github.com/mozilla/sops/issues/305), but as it seems it could be a while till that PR is reviewed and new version is released. And since kustomize-controller has some internal SOPS implementation same thing could be achieved before passing data to SOPS.

Sort SOPS masterkeys so offline decrypt methods are tried first

---

api/v1beta2/kustomization_types.go
config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml

To solve discrepancies between parsing versus validation.
xref: https://github.com/kubernetes/apimachinery/issues/131

api: add custom validation for v1.Duration types

---

.github/workflows/cifuzz.yaml
.github/workflows/e2e.yaml
.github/workflows/scan.yml
Dockerfile
Makefile
config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
config/rbac/role.yaml
controllers/kustomization_generator.go
internal/sops/azkv/config.go

Changes:
- Update Go to 1.19 in CI
- Use Go 1.19 in base image
- Update controller-gen v0.8.0 (v0.7 fails with Go 1.19) and regenerate manifests

Build with Go 1.19

---

controllers/kustomization_controller.go
controllers/kustomization_generator.go
controllers/kustomization_generator_test.go
controllers/testdata/different-filenames/Kustomization/Kustomization
controllers/testdata/different-filenames/Kustomization/deployment.yaml
controllers/testdata/different-filenames/yaml/deployment.yaml
controllers/testdata/different-filenames/yaml/kustomization.yaml
controllers/testdata/different-filenames/yml/deployment.yaml
controllers/testdata/different-filenames/yml/kustomization.yml
go.mod
go.sum

`KustomizeGenerator.WriteFile` now detects alternative kustomization
file names such as `kustomization.yml` and `Kustomization`.
closes #737

Support alternative kustomization file names

---

controllers/kustomization_controller.go
internal/inventory/inventory.go
internal/inventory/inventory_test.go
internal/inventory/testdata/inventory1.yaml
internal/inventory/testdata/inventory2.yaml

Move inventory helpers to internal package and add unit tests.

Refactor: Move inventory helpers to internal package

---

api/v1beta1/kustomization_types.go
api/v1beta2/condition_types.go
api/v1beta2/kustomization_types.go
controllers/kustomization_controller.go
controllers/kustomization_decryptor_test.go
controllers/kustomization_force_test.go
controllers/kustomization_impersonation_test.go
controllers/kustomization_prune_test.go
controllers/kustomization_wait_test.go
controllers/suite_test.go
docs/spec/v1beta2/kustomization.md
go.mod
go.sum
internal/decryptor/decryptor.go
internal/decryptor/decryptor_test.go
internal/generator/generator.go
internal/generator/generator_test.go
internal/generator/varsub.go
main.go

- Make the `Kustomization.status` conform to the Kubernetes kstatus standard
- Make the `Kustomization.status.conditions` conform to the Kubernetes standard conditions
- Improve the reconciliation observability with real-time informations about the actions taken by the controller 
- Adopt `fluxcd/pkg/runtime/conditions` and `fluxcd/pkg/runtime/controller` for status operations 
Test image: `ghcr.io/fluxcd/kustomize-controller:rc-747a2c9e`
This PR introduces a new status condition named `Reconciling` which improves the observability for the actions performed by the controller during a reconciliation run.
The `Reconciling` message reflects the current action being executed e.g.:
- Fetching manifests for revision `X` with a timeout of  `Y`
- Building manifests for revision `X` with a timeout …

Refactor: Adopt Flux runtime conditions and status standards

---

README.md
docs/spec/README.md
docs/spec/v1beta2/README.md
docs/spec/v1beta2/kustomization.md

Changes:
- Explicitly call kustomize-controller a Flux component
- Remove guide form README.md which overlaps with Flux website
- Add links to Flux website
- Make small corrections to the API docs
Ref: #663 #664

Refactor: Remove docs which overlap with Flux website

---

api/v1beta2/kustomization_types.go
config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml

To allow waiting for `HelmRelease` resources with an exceptionally high timeout of `1h` or more.
Related to: https://github.com/fluxcd/helm-controller/pull/549

api: allow configuration of `h` unit for timeouts

---

Dockerfile

LibKSBA is a dependency to GnuPG, which has a CVE that is yet to be patched on Alpine's stable channel. This PR installs GnuPG from the edge channel, and should be reverted once libksba's version 1.6.2 is in main.
https://pkgs.alpinelinux.org/packages?name=libksba&branch=edge
https://gnupg.org/blog/20221017-pepe-left-the-ksba.html

build: Bump gpg to alpine's edge

---

Dockerfile

Creating a minimal nsswitch.conf in Alpine is no longer necessary due to https://git.alpinelinux.org/aports/commit/?id=348653a9ba0701e8e968b3344e72313a9ef334e4

Remove nsswitch.conf creation from Dockerfile

---

controllers/kustomization_fuzzer_test.go
tests/fuzz/README.md
tests/fuzz/oss_fuzz_build.sh
tests/fuzz/oss_fuzz_prebuild.sh

Establish conventions which aligns with what is supported upstream today, whilst expanding on documentation to ensure folks have pointers on how to debug/check for issues going forwards.

build: Fix cifuzz tests and improve fuzz tests' reliability

---

docs/spec/v1beta2/kustomization.md

Document behaviour of atomic fields with server-side apply

---

.github/workflows/e2e.yaml
Dockerfile
config/testdata/impersonation/test.yaml
config/testdata/oci/podinfo.yaml
controllers/kustomization_dependson_test.go

Bump Alpine version to fix the following OS CVEs:
- CVE-2022-41903
- CVE-2022-3515
- CVE-2022-47629 
- CVE-2022-43551
- CVE-2022-23521 
- CVE-2022-43552
An official image is available with zero CVEs at: `ghcr.io/fluxcd/kustomize-controller:rc-949873ae`. To deploy this image on clusters bootstrapped by Flux see https://fluxcd.io/flux/cheatsheets/bootstrap/#test-release-candidates
Ref: https://github.com/fluxcd/flux2/issues/3515

Update Alpine to 3.17

---

Makefile

Create individual make targets for the CRD dependencies so that make can identify that the CRD dependencies have already been downloaded and skip. When the `SOURCE_VER` changes, old CRDs are deleted and new ones are
downloaded, keeping a record of the source CRD versions in `build/.src-crd-<version>` by file name.
Also, introduce `cleanup-crd-deps` make target to delete the previously downloaded CRDs.
Without this, the CRDs were downloaded every single time when running tests:
```console
$ ls config/crd/bases/
buckets.yaml  gitrepositories.yaml  kustomize.toolkit.fluxcd.io_kustomizations.yaml  ocirepositories.yaml
$ make test
...
curl https://raw.githubusercontent.com/fluxcd/source-controller/v0.33.0/config/crd/bases/source.toolkit.fluxcd.io_gitrepositories.yaml > …
```

build: Download CRD deps only when necessary

---

controllers/kustomization_force_test.go
controllers/kustomization_wait_test.go
controllers/suite_test.go
go.mod
go.sum

Update `fluxcd/pkg/runtime` to v0.25.0 which has the new kstatus checker enhancements.
Enable previous kstatus checks and introduce kstatus in-progress checker for testing in-progress status of objects.

Enable kstatus checks

---

internal/features/features.go
main.go

This commit allows the disabling of the caching cluster reader used by
the status poller while waiting and/or checking the health of resources.
Potentially reducing the memory usage of the controller on large scale
clusters, at the cost of an increase in direct API calls.
The feature can be enabled using
`--feature-gates=DisableStatusPollerCache=true`.
Potentially helps aid scenario described in #801

kstatus: allow disabling of caching cluster reader

---

docs/spec/v1/kustomization.md
go.mod
go.sum
internal/sops/azkv/config.go
internal/sops/azkv/keysource.go
internal/sops/keyservice/server.go
internal/sops/keyservice/server_test.go

This pull request adds support for using Azure Workload Identity when decrypting secrets in `Kustomization`
It updates azidentity dependencies to v1.3.0-beta.4 and uses defaultCredentials from environment variables when no secret is set when decrypting with Azure KMS
Closes #795

Support Workload Identity for Azure Vault

---

internal/sops/azkv/keysource.go

At the moment, the envCred logic can't actually set the Azure credentials.
This commit fixes the logic so that the environment variables can actually be used to set the Azure credentials.
There are other issues that come up from this block of code, but those can be dealt with separately.

Fix SOPS azkv envCred

---

docs/spec/v1/kustomization.md

**WARNING**: Since components are alpha level in kustomize this may be removed at any time.
**Add clarification on how to handle component paths**
Currently the advice is that the components are relative to the source root path and after some [investigation](https://github.com/danielloader/fluxcd-kustomization-components/blob/main/clusters/staging/apps.yaml#LL18C24-L18C24) I've found they're relative to the `.spec.path` which itself is an absolute reference to the source root.
Updated the documentation to match.

docs: Clarify the Kustomize components relative paths requirement 

---

internal/controller/kustomization_controller.go

Kustomize controller uses the namespace of the kustomization resource if the sourceRef is empty. However, this policy doesn't applied to dependencies. This can be problematic if the same named `Sources` without explicit namespace is in different namespace.
This commit fixes this issue by using kustomization's namespace when checking dependencies if the namespace in sourceRef is empty.

Use kustomization namespace for empty dependency source namespace

---

.github/workflows/backport.yaml

As per example https://github.com/fluxcd/source-controller/pull/1151

ci: backport: `token` -> `github_token`

---

.github/dependabot.yaml

Beta feature: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups

ci: Group all GH action updates under the same PR

---

internal/controller/kustomization_controller.go
internal/controller/kustomization_controller_test.go

In `Reconcile()` method, move the object deletion above add finalizer. Finalizers can't be set when an object is being deleted.
Found by @hiddeco while working on helm-controller. Refer https://github.com/kubernetes-sigs/cluster-api/commit/cef1cf1d9312088a785c520f49970b1c609ab9ad .

Handle delete before adding finalizer

---

go.mod
go.sum

Detect `field is immutable` errors generated by Kubernetes CEL Transition Rules and Google Cloud admission controllers to recreate objects when force applying. 
Closes: #834

Bump `fluxcd/pkg/ssa` to improve immutable error detection

---

internal/controller/kustomization_controller.go
internal/features/features.go
main.go

Fail the health check as soon as a resource becomes stalled without waiting for the timeout to expire.
For example, if `wait: true` and `timeout: 20m` and a Deployment has reached its deadline progressing in 5m, the controller will not wait for another 15m, it will fail the reconciliation when the Deployment rollout has stalled. 
Note that the fail-fast behavior does not currently work with HelmReleases as these don't have a stalled condition.  We expect to ship stalled conditions in the HelmRelease API v2beta2.
Fix: https://github.com/fluxcd/flux2/discussions/3980
This behavior can be disabled using the `DisableFailFastBehavior` feature flag.

Enable fail-fast behavior for health checks

---

api/v1/kustomization_types.go
config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
docs/api/v1/kustomize.md
docs/spec/v1/kustomizations.md
internal/controller/kustomization_controller.go
main.go

Add a `--interval-jitter-percentage` flag to the controller to add a +/- percentage jitter to the `Kustomization.spec.interval`.
Part of: https://github.com/fluxcd/flux2/issues/4120

controller: jitter requeue interval

---

api/v1/kustomization_types.go
docs/spec/v1/kustomizations.md
go.mod
go.sum
internal/controller/kustomization_controller.go

This PR extends the apply behaviour with two policies  `IfNotPresent` and `Ignore`.
Fix: #936 
Implementation and tests: https://github.com/fluxcd/pkg/pull/625
To change the apply behaviour for specific Kubernetes resources, you can annotate them with:
| Annotation                          | Default    | Values                                                     | Role            |
|-------------------------------------|------------|------------------------------------------------------------|-----------------|
| `kustomize.toolkit.fluxcd.io/ssa`   | `Override` | - `Override`<br/>- `Merge`<br/>- `IfNotPresent`<br/>- `Ignore` | Apply policy    |
| `kustomize.toolkit.fluxcd.io/force` | `Disabled` | - `Enabled`<br/>- `Disabled`                                 | Recreate policy |
| …

Add `IfNotPresent` and `Ignore` SSA policies

---

internal/controller/kustomization_indexers.go

After a Flux upgrade, when SC storage is wiped, SC will remove the `.status.artifact` from sources before it tries to fetch from upstream. Due to this change in SC behaviour, the retry logic of the artifact fetcher in KC no longer works as there is no `.status.artifact.url` to retry for. This PR allows for faster recovery, once the artifact is available in storage, even if the revision is the same, KC will reconcile on the spot instead of waiting for the dependency retry interval.

fix: Retry when artifacts are available in storage

---

go.mod
go.sum

Manual backport of d0e3d4cd08ca5d45e235144e034c08e8f9ee7973.

[release/v1.1.x] build(deps): bump github.com/cyphar/filepath-securejoin

---

internal/features/features.go

As observed in the benchmarks performed with https://github.com/stefanprodan/flux-benchmark, the status poller cache fills all the available memory when reconciliation hundreds of resources in-parallel in a single namespace. Disabling the cache by default makes the controller perform better at scale, but users can reenable the cache with `--feature-gates=DisableStatusPollerCache=false`.
Part of: https://github.com/fluxcd/flux2/issues/4410

Disable status poller cache by default

---

internal/controller/kustomization_controller.go
internal/controller/kustomization_disallowed_managers_test.go
internal/controller/suite_test.go
main.go

Setup a new flag to pass in the names of managers that should be overwritten in the same way that `kubectl` changes are.
Closes #982

Support additional Field Managers in the disallow list

---

internal/controller/kustomization_controller_test.go
internal/controller/testdata/crds/crd.yaml

Prove issue has been fixed: https://github.com/fluxcd/pkg/issues/689

Add test for Namespace custom resource

---

CHANGELOG.md
config/manager/kustomization.yaml
go.mod

Part of: https://github.com/fluxcd/flux2/issues/4410

Release v1.2.0

---

go.mod
go.sum
internal/controller/kustomization_controller.go

This configures a logger on the archive fetcher, to make HTTP errors surface faster when it fails to retrieve the artifact of a source.
Part of: https://github.com/fluxcd/flux2/issues/4472

Log HTTP errors to provide faster feedback

---

.github/dependabot.yaml

Setup dependabot updates for `fluxcd/pkg`.

ci: Enable gomod updates

---

.github/dependabot.yaml

Flux APIs pkg are updated at release time and must be coupled with e2e bumps.

dependabot: Ignore Flux APIs

---

api/v1/kustomization_types.go
api/v1beta1/kustomization_types.go
api/v1beta2/kustomization_types.go

This tag isn't used by controller-tools, only `nonNamespaced` is.
Context: https://cloud-native.slack.com/archives/CLAJ40HV3/p1708794732147909
Tested by running `make generate` and verifying that there is no diff.

Remove `genclient:Namespaced` tag

---

internal/controller/kustomization_controller.go

`controller-runtime` prints this `info`-level warning when a non-nil error is returned alongside a non-zero `ctrl.Result`:
```go
if !result.IsZero() {
log.Info("Warning: Reconciler returned both a non-zero result and a non-nil error. The result will always be ignored if the error is non-nil and the non-nil error causes reqeueuing with exponential backoff. For more details, see: https://pkg.go.dev/sigs.k8s.io/controller-runtime/pkg/reconcile#Reconciler")
}
```
This PR fixes the warning preserving the current behavior (returning the error, which is logged by `controller-runtime`).

Fix requeue warning introduced by controller-runtime

---

internal/sops/keyservice/keyservice.go
internal/sops/keyservice/options.go
internal/sops/keyservice/server.go
internal/sops/keyservice/server_test.go
internal/sops/keyservice/utils_test.go

Follow up: https://github.com/fluxcd/kustomize-controller/pull/656
The remaining files in Flux are glue code for the SOPS integration and can't be moved to the SOPS project. This PR reverts the changes made in #656 and restores the original license header.

Revert SOPS module license to Apache 2.0

---

docs/spec/v1/kustomizations.md
internal/controller/kustomization_varsub_test.go

When using post build substitutions with vars that are numbers or booleans, the reconciliation may fail if the substitution
is for a field that must be of type string. This PR adds a section to the API docs on how to use double quotes vars, and adds unit tests for this procedure.
Fix: https://github.com/fluxcd/flux2/issues/4154
Fix: https://github.com/fluxcd/flux2/issues/1839
Fix: #1096
Fix: #728
Fix: #554

Document how to use numbers and booleans in post build substitutions

---

docs/spec/v1/kustomizations.md
go.mod
go.sum
internal/controller/kustomization_controller.go
internal/controller/kustomization_varsub_test.go
internal/features/features.go
main.go

Changes:
- Replace `github.com/drone/envsubst` with `github.com/fluxcd/pkg/envsubst`. (fix #1107)
- Add `StrictPostBuildSubstitutions` feature flag, when enabled  the post-build substitutions will fail if a variable without a default value is declared in files but is missing from the input vars. (fix: https://github.com/fluxcd/flux2/issues/4694)

Add `StrictPostBuildSubstitutions` feature flag

---

api/v1/kustomization_types.go
config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
docs/api/v1/kustomize.md
docs/spec/v1/kustomizations.md
go.mod
go.sum
internal/controller/kustomization_controller.go
internal/controller/kustomization_transformer_test.go

Closes: #1133 
`.spec.namePrefix` and `.spec.nameSuffix` are optional fields used to specify a prefix and suffix
to be added to the names of all the resources in the Kustomization.
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
name: app
spec:
namePrefix: "prefix-"
nameSuffix: "-suffix"
```

Implement name prefix/suffix transformers

---

docs/spec/v1/kustomizations.md

Remove references to aad pod identity.

Remove deprecated aad pod identity from API docs

---

internal/controller/kustomization_controller.go

The `Mark…` functions in the `conditions` package accept a format string and (optional) arguments, just like `fmt.Printf` and friends.
In many places, the code passed an error message as the format string, causing it to be interpreted as a format string by the `fmt` package. This leads to issues when the message contains percent signs, e.g. URL-encoded values.
This PR adds a format string and shortens `err.Error()` to `err`, which yields the same output.
This change is identical in principle to https://github.com/fluxcd/source-controller/pull/1529.

Fix incorrect use of format strings with the `conditions` package.

---

docs/spec/v1/kustomizations.md

Fixes: https://github.com/fluxcd/flux2/discussions/4979

docs: Clarify `.spec.decryption.secretRef` usage

---

internal/controller/kustomization_controller.go
internal/controller/suite_test.go
main.go

Use the `APIReader` client to bypass the controller runtime cache when checking for dependencies. This allows a Kustomization to depend on other Kustomizations managed by different controller shards.
Fix: #1175

Allow cross-shard dependency check

---

internal/controller/kustomization_decryptor_test.go
internal/controller/testdata/test-dotenv/overlays/component/kustomization.yaml
internal/controller/testdata/test-dotenv/overlays/component/year3.env
internal/controller/testdata/test-dotenv/overlays/kustomization.yaml
internal/decryptor/decryptor.go

Enable decryption of secrets generated by Kustomize components

---

internal/controller/kustomization_controller.go

Suspend and readiness metrics recording removed from Kustomization reconciler.
Refer https://github.com/fluxcd/flux2/issues/5083.

Remove deprecated object metrics

---

api/v1/kustomization_types.go
config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
docs/api/v1/kustomize.md
docs/spec/v1/kustomizations.md
internal/controller/kustomization_controller.go
internal/controller/kustomization_deletion_policy_test.go

The `prune` setting of Kustomizations has a two-fold behavior. When set to `true` FLux will:
1. Ensure stale managed resources are deleted.
2. Garbage collect managed resources when Kustomization is deleted (using a finalizer).
We would like to have 1, but not 2, and this is currently not possible. This PR introduces a new API field allowing control over finalization garbage collection independently of `prune`.
We are using Flux to provision review environments in a multi-tenant environment (shared cluster), and our tenants are not allowed to create Kubernetes namespaces directly. Instead they have to use a custom namespace-scoped resource as a controller for the namespace (and RBAC). This indirect management of namespaces makes it hard to create Kustomizations inside review namespaces. …

Allow control of finalization garbage collection with `.spec.deletionPolicy`

---

api/v1/kustomization_types.go
config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
docs/api/v1/kustomize.md
docs/spec/v1/kustomizations.md
go.mod
go.sum
internal/controller/constants.go
internal/controller/kustomization_controller.go
internal/controller/kustomization_origin_revision_test.go
internal/controller/suite_test.go

Part of: https://github.com/fluxcd/flux2/issues/5148
I have tested this e2e using GitHub:

Add OCI origin revision to events

---

docs/spec/v1/kustomizations.md

A quick one line addition to the docs coming from #1408

docs: mention CEL macros when discussing health check expressions

---

internal/controller/kustomization_controller.go

There are edge cases where a reconciliation can be triggered on a suspended Kustomization, mainly through changes in a source. In these cases a "no-op" reconciliation occurs, which can be confusing for the user. This PR prevents the controller from updating the status and issuing events.
Fix: https://github.com/fluxcd/flux2/issues/5174

Skip emitting events for suspended Kustomizations

---

api/go.mod
api/go.sum
go.mod
go.sum
internal/controller/kustomization_configuration_error_test.go
internal/controller/kustomization_controller.go
internal/features/features.go
main.go

Part of: https://github.com/fluxcd/flux2/issues/5022

[RFC-0010] Introduce feature gate

---

api/v1/kustomization_types.go
config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
docs/api/v1/kustomize.md
docs/spec/v1/kustomizations.md
go.mod
go.sum
internal/controller/kustomization_controller.go
internal/controller/kustomization_deletion_policy_test.go

The `WaitForTermination` deletion policy blocks and waits for the managed resources to be removed from etcd by the Kubernetes garbage collector. The wait time is determined by the `.spec.timeout` field. If a timeout occurs, the controller will log an error and will allow the Kustomization to be deleted while the managed resources will be left in the cluster.
Example:
```yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
name: podinfo
namespace: default
spec:
interval: 30m
retryInterval: 5m
targetNamespace: default
sourceRef:
kind: GitRepository
name: podinfo
path: "./kustomize"
deletionPolicy: WaitForTermination
prune: true
timeout: 2m
```
Fix: #711

Implement `WaitForTermination` deletion policy

---

go.mod
go.sum

Upgrading `pkg/ssa` to version `0.49.0` 
Includes fix for #800: Remove CABundle from CRDs if cert is invalid
@matheuscscp

Bump pkg/ssa to v0.49.0 for CABundle validation fix

---

internal/sops/awskms/region.go
internal/sops/awskms/region_test.go

Fixes #1477 
In kustomize-controller 1.6.0 a new logic was introduced for getting the AWS region from the KMS key ARN that did not account for the `aws-us-gov` and `aws-cn` ARN partitions. This logic would produce errors like the one below, where `arn` is mistakenly used as the region extracted by `GetRegionFromKMSARN()` in the STS endpoint:
```
STS: AssumeRoleWithWebIdentity, https response error\n   StatusCode: 0, RequestID:
, request send failed, Post\n \"https://sts.arn.amazonaws.com/\": dial tcp:
lookupts.arn.amazonaws.com on 10.100.0.10:53: no such host
```
The endpoint comes out as `https://sts.arn.amazonaws.com/`, when it should be something like `https://sts.us-gov-west-1.amazonaws.com/`.
This PR fixes the issue by using the same regex that SOPS uses for extracting the region.

Fix regression in STS endpoint for SOPS decryption with AWS KMS in US Gov partition

---

go.mod
go.sum
internal/controller/kustomization_configuration_error_test.go
internal/decryptor/decryptor.go
main.go

[RFC-0010] Add multi-tenancy lockdown for decryption and kubeconfig

---

.gitignore
Makefile
api/v1/reference_types.go
config/crd/bases/kustomize.toolkit.fluxcd.io_kustomizations.yaml
config/default/kustomization.yaml
docs/spec/v1/kustomizations.md
go.mod
go.sum
internal/controller/kustomization_acl_test.go
internal/controller/kustomization_controller.go
internal/controller/kustomization_externalartifact_test.go
internal/controller/kustomization_indexers.go
internal/controller/kustomization_manager.go
internal/controller/suite_test.go
internal/features/features.go
main.go

Part of: https://github.com/fluxcd/flux2/issues/5504

[RFC-0012] Add support for `ExternalArtifact` source type

---

go.mod
go.sum
internal/controller/kustomization_controller.go
internal/controller/kustomization_wait_test.go
internal/features/features.go
main.go

This PR introduces the feature gate `CancelHealthCheckOnNewRevision` for allowing health checks to be cancelled earlier in case a new revision of the source is observed.
Co-authored-by: @trashhalo (xref: https://github.com/fluxcd/kustomize-controller/pull/1518)
Includes: https://github.com/fluxcd/pkg/pull/1033

Add feature gate to cancel health checks on new revisions
